"""
fixer.py – Safe fixes and backup management for Project Doctor.
"""

import shutil
from datetime import datetime
from pathlib import Path
from typing import List, Optional


class BackupManager:
    """Creates timestamped backups of the project folder."""

    def __init__(self, backup_root: Path):
        self.backup_root = backup_root
        self.backup_root.mkdir(parents=True, exist_ok=True)

    def create_backup(self, project_path: Path) -> Path:
        """Copy the entire project into a timestamped backup folder."""
        timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
        backup_dir = self.backup_root / timestamp
        shutil.copytree(project_path, backup_dir, dirs_exist_ok=True)
        return backup_dir

    def list_backups(self) -> List[Path]:
        """Return list of backup directories."""
        if not self.backup_root.exists():
            return []
        return sorted([d for d in self.backup_root.iterdir() if d.is_dir()], reverse=True)

    def restore_backup(self, backup_dir: Path, target_path: Path) -> None:
        """Restore a backup to the target path, overwriting existing."""
        if target_path.exists():
            shutil.rmtree(target_path)
        shutil.copytree(backup_dir, target_path)


class SafeFixer:
    """Applies safe fixes after confirmation and backup."""

    def __init__(self, backup_manager: BackupManager):
        self.backup_manager = backup_manager

    def create_gitignore(self, project_path: Path) -> bool:
        """
        Create a .gitignore with recommended Python entries.
        Returns True if created, False if already exists.
        """
        gitignore_path = project_path / ".gitignore"
        if gitignore_path.exists():
            return False

        # Backup first
        backup = self.backup_manager.create_backup(project_path)
        print(f"Backup created at: {backup}")

        entries = [
            "__pycache__/",
            "*.py[cod]",
            ".venv/",
            "venv/",
            ".env",
            "*.log",
            ".DS_Store",
        ]
        gitignore_path.write_text("\n".join(entries) + "\n", encoding="utf-8")
        return True

    def generate_requirements(self, project_path: Path) -> bool:
        """
        Generate a requirements.txt from installed packages (pip freeze).
        Returns True if created, False if already exists.
        """
        req_path = project_path / "requirements.txt"
        if req_path.exists():
            return False

        # Backup first
        backup = self.backup_manager.create_backup(project_path)
        print(f"Backup created at: {backup}")

        # Use pip freeze to generate
        import subprocess
        result = subprocess.run(["pip", "freeze"], capture_output=True, text=True)
        if result.returncode == 0:
            req_path.write_text(result.stdout, encoding="utf-8")
            return True
        else:
            # fallback: write empty
            req_path.write_text("# Generated by Project Doctor\n", encoding="utf-8")
            return True